pipeline {
    agent {
        docker {
            image 'python:3.10-alpine'
        }
    }
    stages {
        stage('Run Python Script') {
            steps {
                sh 'python /python-test/add2vals.py'
            }
        }
    }
}
